# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "di-maas-v0.1"
  config.vm.host_name = "di-maas01"

  config.vm.network :forwarded_port, guest: 8080, host: 18081
  config.vm.network :private_network, ip: "192.168.44.101"
end 
