# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos6.3"
  config.vm.host_name = "cobbler01"

  config.vm.network :forwarded_port, guest: 80, host: 18080
  config.vm.network :public_network
  config.vm.network :private_network, ip: "192.168.44.102"
end 
